"""Admin-backend operations that authenticate a caller but carry no
permission-bearing dependency: a bare ``get_current_user`` /
``verify_service_or_oidc`` (any signed-in role gets through the dependency;
some handlers check a permission themselves) or ``_guest_mode_config_auth``.

Frozen when the route-auth gate started requiring permission metadata
(ATHENA-168 reviews and narrows them). ``test_route_auth_population.py``
compares this set exactly: a new route with a bare user dependency fails
until it uses ``require_user_permission`` / ``require_service_or_user_permission``
(or it's added here with a reason in review), and moving one of these to a
factory fails until it's removed from here.

Grouped by the module that defines the endpoint. Generated from the live
route walk; keep it sorted.
"""

LEGACY_PERMISSIONLESS_BY_MODULE = {
    'alerts': [
        'DELETE /api/alerts/{alert_id}',
        'GET /api/alerts',
        'GET /api/alerts/active/count',
        'GET /api/alerts/stats',
        'GET /api/alerts/{alert_id}',
        'PATCH /api/alerts/{alert_id}',
        'POST /api/alerts/acknowledge-all',
    ],
    'analytics': [
        'GET /api/analytics/intents',
        'GET /api/analytics/latency-distribution',
        'GET /api/analytics/pipeline-stats',
        'GET /api/analytics/query-logs',
    ],
    'audit': [
        'GET /api/audit',
        'GET /api/audit/recent',
        'GET /api/audit/resource/{resource_type}/{resource_id}',
        'GET /api/audit/stats',
        'GET /api/audit/user/{user_id}',
        'POST /api/audit/{audit_id}/undo',
    ],
    'base_knowledge': [
        'DELETE /api/base-knowledge/{knowledge_id}',
        'GET /api/base-knowledge',
        'GET /api/base-knowledge/public',
        'GET /api/base-knowledge/settings',
        'GET /api/base-knowledge/{knowledge_id}',
        'POST /api/base-knowledge',
        'POST /api/base-knowledge/bulk',
        'PUT /api/base-knowledge/settings',
        'PUT /api/base-knowledge/{knowledge_id}',
    ],
    'cloud_llm_usage': [
        'DELETE /api/cloud-llm-usage/purge',
        'GET /api/cloud-llm-usage/cost-alerts',
        'GET /api/cloud-llm-usage/cost-breakdown',
    ],
    'cloud_providers': [
        'DELETE /api/cloud-providers/{provider}/api-key',
        'PATCH /api/cloud-providers/{provider}',
        'POST /api/cloud-providers/health/{provider}',
        'POST /api/cloud-providers/pricing',
        'POST /api/cloud-providers/{provider}/setup',
        'PUT /api/cloud-providers/{provider}',
    ],
    'component_models': [
        'GET /api/component-models',
        'GET /api/component-models/available-models',
        'POST /api/component-models/invalidate-cache',
        'POST /api/component-models/{component_name}/toggle',
        'PUT /api/component-models/{component_name}',
    ],
    'conversation': [
        'DELETE /api/conversation/sports-teams/{team_id}',
        'GET /api/conversation/analytics',
        'GET /api/conversation/analytics/summary',
        'GET /api/conversation/clarification',
        'GET /api/conversation/clarification/types',
        'GET /api/conversation/clarification/types/{type_name}',
        'GET /api/conversation/device-rules',
        'GET /api/conversation/device-rules/{device_type}',
        'GET /api/conversation/settings',
        'GET /api/conversation/sports-teams',
        'POST /api/conversation/sports-teams',
        'PUT /api/conversation/clarification',
        'PUT /api/conversation/clarification/types/{type_name}',
        'PUT /api/conversation/device-rules/{device_type}',
        'PUT /api/conversation/settings',
        'PUT /api/conversation/sports-teams/{team_id}',
    ],
    'conversations': [
        'GET /api/conversations',
        'GET /api/conversations/stats',
        'GET /api/conversations/{conversation_id}',
        'POST /api/conversations/turns/{turn_id}/evaluate',
    ],
    'dashboard': [
        'GET /api/dashboard',
        'GET /api/dashboard/integrations',
        'GET /api/dashboard/quick-stats',
    ],
    'devices': [
        'DELETE /api/devices/{device_id}',
        'GET /api/devices',
        'GET /api/devices/zones',
        'GET /api/devices/{device_id}',
        'POST /api/devices',
        'POST /api/devices/{device_id}/heartbeat',
        'PUT /api/devices/{device_id}',
    ],
    'directions_settings': [
        'GET /api/directions-settings',
        'GET /api/directions-settings/{setting_key}',
        'POST /api/directions-settings/reset',
        'PUT /api/directions-settings/{setting_id}',
    ],
    'emerging_intents': [
        'GET /api/emerging-intents',
        'GET /api/emerging-intents/stats',
        'GET /api/emerging-intents/{intent_id}',
        'GET /api/intent-metrics/stats',
        'POST /api/emerging-intents/merge',
        'POST /api/emerging-intents/{intent_id}/promote',
        'POST /api/emerging-intents/{intent_id}/reject',
        'POST /api/emerging-intents/{intent_id}/review',
    ],
    'escalation': [
        'DELETE /api/escalation/override/{session_id}',
        'DELETE /api/escalation/presets/{preset_id}',
        'DELETE /api/escalation/rules/{rule_id}',
        'GET /api/escalation/events',
        'GET /api/escalation/events/recent',
        'GET /api/escalation/events/stats',
        'GET /api/escalation/override/{session_id}',
        'GET /api/escalation/overrides/active',
        'GET /api/escalation/presets',
        'GET /api/escalation/presets/{preset_id}',
        'GET /api/escalation/presets/{preset_id}/rules',
        'GET /api/escalation/rules/{rule_id}',
        'POST /api/escalation/override',
        'POST /api/escalation/presets',
        'POST /api/escalation/presets/{preset_id}/clone',
        'POST /api/escalation/presets/{preset_id}/rules',
        'PUT /api/escalation/presets/{preset_id}',
        'PUT /api/escalation/presets/{preset_id}/activate',
        'PUT /api/escalation/rules/{rule_id}',
        'PUT /api/escalation/rules/{rule_id}/toggle',
    ],
    'external_api_keys': [
        'DELETE /api/external-api-keys/{service_name}',
        'GET /api/external-api-keys',
        'GET /api/external-api-keys/{service_name}',
        'POST /api/external-api-keys',
        'PUT /api/external-api-keys/{service_name}',
    ],
    'features': [
        'GET /api/features',
        'GET /api/features/impact/analysis',
        'GET /api/features/what-if/scenarios',
        'GET /api/features/{feature_id}',
        'PUT /api/features/{feature_id}',
        'PUT /api/features/{feature_id}/config',
        'PUT /api/features/{feature_id}/toggle',
    ],
    'follow_me': [
        'DELETE /api/follow-me/excluded/{room_name}',
        'DELETE /api/follow-me/rooms/{room_name}',
        'GET /api/follow-me/config',
        'GET /api/follow-me/excluded',
        'GET /api/follow-me/rooms',
        'POST /api/follow-me/excluded',
        'POST /api/follow-me/rooms',
        'PUT /api/follow-me/config',
        'PUT /api/follow-me/rooms/{room_name}',
    ],
    'gateway_config': [
        'GET /api/gateway-config',
        'PATCH /api/gateway-config',
        'POST /api/gateway-config/reset',
    ],
    'guest_mode': [
        'DELETE /api/guest-mode/events/{event_id}',
        'DELETE /api/guest-mode/test-data',
        'GET /api/guest-mode/config',
        'GET /api/guest-mode/events',
        'GET /api/guest-mode/events/current',
        'GET /api/guest-mode/events/upcoming',
        'GET /api/guest-mode/events/{event_id}',
        'GET /api/guest-mode/history',
        'GET /api/guest-mode/mode-status',
        'GET /api/guest-mode/overrides',
        'PATCH /api/guest-mode/config',
        'PATCH /api/guest-mode/events/{event_id}',
        'POST /api/guest-mode/config',
        'POST /api/guest-mode/events',
    ],
    'guests': [
        'DELETE /api/guests/{guest_id}',
        'POST /api/guests',
        'PUT /api/guests/{guest_id}',
    ],
    'ha_pipelines': [
        'POST /api/ha-pipelines/pipelines/set-preferred',
    ],
    'hallucination_checks': [
        'DELETE /api/hallucination-checks/{check_id}',
        'GET /api/hallucination-checks',
        'GET /api/hallucination-checks/{check_id}',
        'POST /api/hallucination-checks',
        'PUT /api/hallucination-checks/{check_id}',
    ],
    'integrations': [
        'GET /api/integrations/',
        'GET /api/integrations/{integration_id}/status',
    ],
    'intent_routing': [
        'DELETE /api/intent-routing/patterns/{pattern_id}',
        'DELETE /api/intent-routing/providers/{provider_id}',
        'DELETE /api/intent-routing/routing/{routing_id}',
        'GET /api/intent-routing/patterns',
        'GET /api/intent-routing/providers',
        'GET /api/intent-routing/routing',
        'GET /api/intent-routing/strategy/configs',
        'POST /api/intent-routing/patterns',
        'POST /api/intent-routing/providers',
        'POST /api/intent-routing/routing',
        'POST /api/intent-routing/strategy/configs/{intent_name}/toggle',
        'PUT /api/intent-routing/patterns/{pattern_id}',
        'PUT /api/intent-routing/providers/{provider_id}',
        'PUT /api/intent-routing/routing/{routing_id}',
        'PUT /api/intent-routing/strategy/configs/{intent_name}',
    ],
    'llm_backends': [
        'DELETE /api/llm-backends/{backend_id}',
        'GET /api/llm-backends',
        'GET /api/llm-backends/metrics',
        'GET /api/llm-backends/{backend_id}',
        'POST /api/llm-backends',
        'POST /api/llm-backends/{backend_id}/toggle',
        'PUT /api/llm-backends/{backend_id}',
    ],
    'main': [
        'GET /api/auth/me',
        'GET /api/status',
        'GET /auth/me',
        'GET /status',
        'POST /api/auth/ws-ticket',
    ],
    'mcp_security': [
        'DELETE /api/mcp-security/domains/allow/{domain}',
        'DELETE /api/mcp-security/domains/block/{domain}',
        'GET /api/mcp-security',
        'GET /api/mcp-security/approval-queue',
        'POST /api/mcp-security/approval-queue/{item_id}/review',
        'POST /api/mcp-security/domains/allow',
        'POST /api/mcp-security/domains/block',
        'PUT /api/mcp-security',
    ],
    'memories': [
        'DELETE /api/memories/{memory_id}',
        'GET /api/memories/config',
        'GET /api/memories/guest-sessions',
        'GET /api/memories/guest-sessions/{session_id}',
        'GET /api/memories/{memory_id}',
        'POST /api/memories',
        'POST /api/memories/config/seed-defaults',
        'POST /api/memories/guest-sessions',
        'POST /api/memories/{memory_id}/promote',
        'PUT /api/memories/config/{key}',
        'PUT /api/memories/{memory_id}',
    ],
    'model_config': [
        'DELETE /api/model-configs/{config_id}',
        'GET /api/model-configs',
        'GET /api/model-configs/{config_id}',
        'POST /api/model-configs',
        'POST /api/model-configs/{config_id}/apply-preset',
        'POST /api/model-configs/{config_id}/toggle',
        'PUT /api/model-configs/{config_id}',
    ],
    'model_downloads': [
        'DELETE /api/model-downloads/{download_id}',
        'GET /api/model-downloads',
        'GET /api/model-downloads/downloaded/files',
        'GET /api/model-downloads/repo/{repo_id:path}/files',
        'GET /api/model-downloads/{download_id}',
        'POST /api/model-downloads',
        'POST /api/model-downloads/search',
        'POST /api/model-downloads/{download_id}/cancel',
        'POST /api/model-downloads/{download_id}/import-ollama',
        'POST /api/model-downloads/{download_id}/retry',
    ],
    'multi_intent': [
        'DELETE /api/multi-intent/chains/{chain_id}',
        'GET /api/multi-intent/chains',
        'GET /api/multi-intent/chains/{chain_id}',
        'GET /api/multi-intent/config',
        'POST /api/multi-intent/chains',
        'PUT /api/multi-intent/chains/{chain_id}',
        'PUT /api/multi-intent/config',
    ],
    'music_config': [
        'DELETE /api/music-config/genres/{genre}',
        'DELETE /api/music-config/spotify-accounts/{account_id}',
        'GET /api/music-config',
        'GET /api/music-config/artists/search',
        'GET /api/music-config/genres',
        'GET /api/music-config/spotify-accounts',
        'POST /api/music-config/spotify-accounts',
        'POST /api/music-config/test-connection',
        'PUT /api/music-config',
        'PUT /api/music-config/genres',
    ],
    'oss_profiles': [
        'GET /api/oss-profiles/effective-config',
        'GET /api/oss-profiles/runtime-sync',
        'GET /api/oss-profiles/status',
        'POST /api/oss-profiles/apply',
        'POST /api/oss-profiles/fields/detach',
        'POST /api/oss-profiles/fields/reset',
        'POST /api/oss-profiles/install-model',
        'POST /api/oss-profiles/preview',
        'POST /api/oss-profiles/records/detach',
        'POST /api/oss-profiles/records/reset',
        'POST /api/oss-profiles/runtime-sync/retry',
    ],
    'performance_presets': [
        'DELETE /api/presets/{preset_id}',
        'GET /api/presets',
        'GET /api/presets/active',
        'GET /api/presets/{preset_id}',
        'POST /api/presets',
        'POST /api/presets/capture-current',
        'POST /api/presets/{preset_id}/activate',
        'POST /api/presets/{preset_id}/duplicate',
        'PUT /api/presets/{preset_id}',
    ],
    'policies': [
        'DELETE /api/policies/{policy_id}',
        'GET /api/policies',
        'GET /api/policies/{policy_id}',
        'GET /api/policies/{policy_id}/versions',
        'POST /api/policies',
        'POST /api/policies/{policy_id}/rollback/{version}',
        'PUT /api/policies/{policy_id}',
    ],
    'rag_connectors': [
        'DELETE /api/rag-connectors/{connector_id}',
        'GET /api/rag-connectors',
        'GET /api/rag-connectors/{connector_id}',
        'GET /api/rag-connectors/{connector_id}/cache',
        'GET /api/rag-connectors/{connector_id}/stats',
        'POST /api/rag-connectors',
        'POST /api/rag-connectors/{connector_id}/disable',
        'POST /api/rag-connectors/{connector_id}/enable',
        'POST /api/rag-connectors/{connector_id}/test',
        'PUT /api/rag-connectors/{connector_id}',
    ],
    'rag_service_bypass': [
        'DELETE /api/rag-service-bypass/{service_name}',
        'POST /api/rag-service-bypass/{service_name}/toggle',
        'PUT /api/rag-service-bypass/{service_name}',
    ],
    'room_audio': [
        'DELETE /api/room-audio/{config_id}',
        'GET /api/room-audio',
        'GET /api/room-audio/discover/entities',
        'GET /api/room-audio/{room_name}',
        'POST /api/room-audio',
        'POST /api/room-audio/{config_id}/test',
        'PUT /api/room-audio/{config_id}',
    ],
    'room_groups': [
        'DELETE /api/room-groups/{group_id}',
        'DELETE /api/room-groups/{group_id}/aliases/{alias_id}',
        'DELETE /api/room-groups/{group_id}/members/{member_id}',
        'GET /api/room-groups/{group_id}',
        'POST /api/room-groups',
        'POST /api/room-groups/{group_id}/aliases',
        'POST /api/room-groups/{group_id}/members',
        'PUT /api/room-groups/{group_id}',
    ],
    'room_tv': [
        'DELETE /api/room-tv/apps/{app_id}',
        'DELETE /api/room-tv/{config_id}',
        'GET /api/room-tv',
        'GET /api/room-tv/apps/all',
        'GET /api/room-tv/apps/sync/{entity_id:path}',
        'GET /api/room-tv/control/{room_name}/state',
        'GET /api/room-tv/discover',
        'GET /api/room-tv/{room_name}',
        'POST /api/room-tv',
        'POST /api/room-tv/apps',
        'POST /api/room-tv/control/{room_name}/launch',
        'POST /api/room-tv/control/{room_name}/power',
        'POST /api/room-tv/control/{room_name}/remote',
        'PUT /api/room-tv/apps/{app_id}',
        'PUT /api/room-tv/features/{feature_name}',
        'PUT /api/room-tv/{config_id}',
    ],
    'secrets': [
        'DELETE /api/secrets/{secret_id}',
        'GET /api/secrets',
        'GET /api/secrets/{secret_id}',
        'GET /api/secrets/{secret_id}/reveal',
        'POST /api/secrets',
        'PUT /api/secrets/{secret_id}',
    ],
    'service_control': [
        'GET /api/service-control',
        'GET /api/service-control/containers/status',
        'GET /api/service-control/ollama/health',
        'GET /api/service-control/ollama/models',
        'POST /api/service-control/ollama/models/{model_name:path}/load',
        'POST /api/service-control/ollama/models/{model_name:path}/unload',
        'POST /api/service-control/ollama/restart',
        'POST /api/service-control/ollama/start',
        'POST /api/service-control/ollama/stop',
        'POST /api/service-control/port/{port}/restart',
        'POST /api/service-control/port/{port}/start',
        'POST /api/service-control/port/{port}/stop',
        'POST /api/service-control/refresh-status',
        'POST /api/service-control/{service_name}/restart',
        'POST /api/service-control/{service_name}/start',
        'POST /api/service-control/{service_name}/stop',
    ],
    'service_registry': [
        'DELETE /api/service-registry/services/{service_name}',
        'GET /api/service-registry/services',
        'POST /api/service-registry/services',
        'POST /api/service-registry/services/poll-now',
        'POST /api/service-registry/services/{service_name}/check',
        'POST /api/service-registry/services/{service_name}/refresh',
        'POST /api/service-registry/services/{service_name}/toggle',
    ],
    'services': [
        'DELETE /api/services/{service_id}',
        'GET /api/services',
        'GET /api/services/gateway/health',
        'GET /api/services/mlx/health',
        'GET /api/services/ollama/health',
        'GET /api/services/orchestrator/health',
        'GET /api/services/qdrant/health',
        'GET /api/services/redis/health',
        'GET /api/services/{service_id}',
        'POST /api/services',
        'POST /api/services/status/all',
        'POST /api/services/{service_id}/check',
        'PUT /api/services/{service_id}',
    ],
    'settings': [
        'GET /api/settings/assistant-profile',
        'GET /api/settings/oidc',
        'GET /api/settings/privacy',
        'POST /api/settings/assistant-profile',
        'POST /api/settings/directions-origin-placeholders',
        'POST /api/settings/house-layout',
        'POST /api/settings/llm-memory',
        'POST /api/settings/oidc',
        'POST /api/settings/ollama-url',
        'POST /api/settings/privacy',
        'POST /api/settings/tool-proposals',
    ],
    'site_scraper': [
        'GET /api/site-scraper/config',
        'PUT /api/site-scraper/config',
    ],
    'sms': [
        'DELETE /api/sms/scheduled/{scheduled_id}',
        'DELETE /api/sms/templates/{template_id}',
        'DELETE /api/tips/{tip_id}',
        'GET /api/sms/costs/by-stay',
        'GET /api/sms/costs/summary',
        'GET /api/sms/history',
        'GET /api/sms/history/{history_id}',
        'GET /api/sms/incoming',
        'GET /api/sms/incoming/{incoming_id}',
        'GET /api/sms/preferences/{event_id}',
        'GET /api/sms/scheduled',
        'GET /api/sms/scheduled/{scheduled_id}',
        'GET /api/sms/settings',
        'GET /api/sms/templates',
        'GET /api/sms/templates/{template_id}',
        'GET /api/tips',
        'GET /api/tips/{tip_id}',
        'PATCH /api/sms/scheduled/{scheduled_id}',
        'PATCH /api/sms/templates/{template_id}',
        'PATCH /api/tips/{tip_id}',
        'POST /api/sms/scheduled',
        'POST /api/sms/send',
        'POST /api/sms/templates',
        'POST /api/tips',
        'PUT /api/sms/preferences/{event_id}',
        'PUT /api/sms/settings',
    ],
    'telemetry': [
        'GET /api/telemetry/status',
        'POST /api/telemetry/reset-identity',
        'POST /api/telemetry/send',
        'PUT /api/telemetry/settings',
    ],
    'tool_calling': [
        'DELETE /api/tool-calling/api-key-requirements/{requirement_id}',
        'DELETE /api/tool-calling/tools/{tool_id}',
        'GET /api/tool-calling/api-keys/available',
        'GET /api/tool-calling/mcp/status',
        'GET /api/tool-calling/metrics',
        'GET /api/tool-calling/metrics/aggregated',
        'GET /api/tool-calling/settings',
        'GET /api/tool-calling/tools',
        'GET /api/tool-calling/tools-with-api-keys',
        'GET /api/tool-calling/tools/stats',
        'GET /api/tool-calling/tools/{tool_id}',
        'GET /api/tool-calling/tools/{tool_id}/api-keys',
        'GET /api/tool-calling/triggers',
        'POST /api/tool-calling/mcp/discover',
        'POST /api/tool-calling/refresh',
        'POST /api/tool-calling/tools',
        'POST /api/tool-calling/tools/by-name/{tool_name}/toggle',
        'POST /api/tool-calling/tools/{tool_id}/api-keys',
        'PUT /api/tool-calling/api-key-requirements/{requirement_id}',
        'PUT /api/tool-calling/settings',
        'PUT /api/tool-calling/tools/{tool_id}',
        'PUT /api/tool-calling/tools/{tool_id}/toggle',
        'PUT /api/tool-calling/triggers/{trigger_id}',
        'PUT /api/tool-calling/triggers/{trigger_id}/toggle',
    ],
    'tool_proposals': [
        'DELETE /api/tool-proposals/{proposal_id}',
        'POST /api/tool-proposals/{proposal_id}/approve',
        'POST /api/tool-proposals/{proposal_id}/reject',
    ],
    'user_api_keys': [
        'DELETE /api/user-api-keys/{key_id}',
        'GET /api/user-api-keys',
        'GET /api/user-api-keys/{key_id}',
        'POST /api/user-api-keys',
    ],
    'user_sessions': [
        'DELETE /api/user-sessions/{session_id}',
    ],
    'users': [
        'DELETE /api/users/{user_id}',
        'GET /api/users',
        'GET /api/users/me/permissions',
        'GET /api/users/roles',
        'GET /api/users/{user_id}',
        'POST /api/users',
        'POST /api/users/me/password',
        'POST /api/users/{user_id}/password',
        'POST /api/users/{user_id}/reactivate',
        'PUT /api/users/{user_id}',
    ],
    'validation_models': [
        'DELETE /api/validation-models/{model_id}',
        'GET /api/validation-models',
        'GET /api/validation-models/{model_id}',
        'POST /api/validation-models',
        'PUT /api/validation-models/{model_id}',
    ],
    'voice_automations': [
        'DELETE /api/voice-automations/{automation_id}',
        'GET /api/voice-automations/{automation_id}',
    ],
    'voice_config': [
        'POST /api/voice-config/restart-services',
        'POST /api/voice-config/stt/set-active',
        'POST /api/voice-config/tts/set-active',
        'PUT /api/voice-config/services/{service_type}',
    ],
    'voice_interfaces': [
        'DELETE /api/voice-interfaces/{interface_name}',
        'GET /api/voice-interfaces',
        'GET /api/voice-interfaces/engines/stt',
        'GET /api/voice-interfaces/engines/tts',
        'GET /api/voice-interfaces/{interface_name}',
        'POST /api/voice-interfaces',
        'PUT /api/voice-interfaces/{interface_name}',
    ],
    'voice_tests': [
        'GET /api/voice-tests/tests/history',
        'POST /api/voice-tests/feedback',
        'POST /api/voice-tests/llm/test',
        'POST /api/voice-tests/pipeline/test',
        'POST /api/voice-tests/rag/test',
        'POST /api/voice-tests/stt/test',
        'POST /api/voice-tests/tts/test',
    ],
}

LEGACY_PERMISSIONLESS = frozenset(
    tuple(op.split(" ", 1)) for ops in LEGACY_PERMISSIONLESS_BY_MODULE.values() for op in ops
)
LEGACY_PERMISSIONLESS_COUNT = 454
