blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/jstuart0/project-athena-oss/discussions
    about: Please ask open-ended questions in Discussions instead of opening an issue.
