"""Add LLM backend registry

Revision ID: 93bea4659785
Revises: 003
Create Date: 2025-11-15 11:26:03.135698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93bea4659785'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_backends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('backend_type', sa.String(length=32), nullable=False),
    sa.Column('endpoint_url', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('avg_tokens_per_sec', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('total_errors', sa.Integer(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature_default', sa.Float(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_backends_backend_type', 'llm_backends', ['backend_type'], unique=False)
    op.create_index('idx_llm_backends_enabled', 'llm_backends', ['enabled'], unique=False)
    op.create_index('idx_llm_backends_model_name', 'llm_backends', ['model_name'], unique=False)
    op.create_index(op.f('ix_llm_backends_model_name'), 'llm_backends', ['model_name'], unique=True)
    # COMMENTED OUT - Legacy tables, keep for now
    # op.drop_table('config_audit_log')
    # op.drop_table('admin_users')
    # op.drop_table('admin_sessions')
    op.alter_column('clarification_settings', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('clarification_settings', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('clarification_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_clarification_settings_singleton', table_name='clarification_settings')
    op.alter_column('clarification_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('clarification_types', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('clarification_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('clarification_types_type_key', 'clarification_types', type_='unique')
    op.drop_index('idx_clarification_types_priority', table_name='clarification_types')
    op.create_index('idx_clarification_types_priority', 'clarification_types', ['priority'], unique=False)
    op.create_index(op.f('ix_clarification_types_type'), 'clarification_types', ['type'], unique=True)
    op.alter_column('conversation_analytics', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_analytics_timestamp', table_name='conversation_analytics')
    op.create_index('idx_analytics_timestamp', 'conversation_analytics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_conversation_analytics_event_type'), 'conversation_analytics', ['event_type'], unique=False)
    op.create_index(op.f('ix_conversation_analytics_session_id'), 'conversation_analytics', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_analytics_timestamp'), 'conversation_analytics', ['timestamp'], unique=False)
    op.alter_column('conversation_settings', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_settings', 'use_context',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_settings', 'max_messages',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_settings', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_settings', 'cleanup_interval_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_settings', 'session_ttl_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_settings', 'max_llm_history_messages',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_conversation_settings_singleton', table_name='conversation_settings')
    op.alter_column('device_disambiguation_rules', 'requires_disambiguation',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('device_disambiguation_rules', 'min_entities_for_clarification',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('device_disambiguation_rules', 'include_all_option',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('device_disambiguation_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_device_type', table_name='device_disambiguation_rules')
    op.create_index('idx_device_type_enabled', 'device_disambiguation_rules', ['device_type', 'requires_disambiguation'], unique=False)
    op.create_index(op.f('ix_device_disambiguation_rules_device_type'), 'device_disambiguation_rules', ['device_type'], unique=True)
    op.alter_column('sports_team_disambiguation', 'requires_disambiguation',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sports_team_disambiguation', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_sports_team_disambiguation_team_name'), 'sports_team_disambiguation', ['team_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sports_team_disambiguation_team_name'), table_name='sports_team_disambiguation')
    op.alter_column('sports_team_disambiguation', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sports_team_disambiguation', 'requires_disambiguation',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_device_disambiguation_rules_device_type'), table_name='device_disambiguation_rules')
    op.drop_index('idx_device_type_enabled', table_name='device_disambiguation_rules')
    op.create_index('idx_device_type', 'device_disambiguation_rules', ['device_type'], unique=False)
    op.alter_column('device_disambiguation_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('device_disambiguation_rules', 'include_all_option',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('device_disambiguation_rules', 'min_entities_for_clarification',
               existing_type=sa.INTEGER(),
               server_default=sa.text('2'),
               existing_nullable=False)
    op.alter_column('device_disambiguation_rules', 'requires_disambiguation',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_index('idx_conversation_settings_singleton', 'conversation_settings', [sa.text('(id IS NOT NULL)')], unique=False)
    op.alter_column('conversation_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversation_settings', 'max_llm_history_messages',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('conversation_settings', 'session_ttl_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3600'),
               existing_nullable=False)
    op.alter_column('conversation_settings', 'cleanup_interval_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_nullable=False)
    op.alter_column('conversation_settings', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1800'),
               existing_nullable=False)
    op.alter_column('conversation_settings', 'max_messages',
               existing_type=sa.INTEGER(),
               server_default=sa.text('20'),
               existing_nullable=False)
    op.alter_column('conversation_settings', 'use_context',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('conversation_settings', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_conversation_analytics_timestamp'), table_name='conversation_analytics')
    op.drop_index(op.f('ix_conversation_analytics_session_id'), table_name='conversation_analytics')
    op.drop_index(op.f('ix_conversation_analytics_event_type'), table_name='conversation_analytics')
    op.drop_index('idx_analytics_timestamp', table_name='conversation_analytics')
    op.create_index('idx_analytics_timestamp', 'conversation_analytics', [sa.text('timestamp DESC')], unique=False)
    op.alter_column('conversation_analytics', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_clarification_types_type'), table_name='clarification_types')
    op.drop_index('idx_clarification_types_priority', table_name='clarification_types')
    op.create_index('idx_clarification_types_priority', 'clarification_types', [sa.text('priority DESC')], unique=False)
    op.create_unique_constraint('clarification_types_type_key', 'clarification_types', ['type'])
    op.alter_column('clarification_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clarification_types', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('clarification_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_index('idx_clarification_settings_singleton', 'clarification_settings', [sa.text('(id IS NOT NULL)')], unique=False)
    op.alter_column('clarification_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clarification_settings', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('300'),
               existing_nullable=False)
    op.alter_column('clarification_settings', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_table('admin_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], name='admin_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='admin_sessions_pkey'),
    sa.UniqueConstraint('session_token', name='admin_sessions_session_token_key')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('admin_users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admin_users_pkey'),
    sa.UniqueConstraint('email', name='admin_users_email_key'),
    sa.UniqueConstraint('username', name='admin_users_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('config_audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], name='config_audit_log_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='config_audit_log_pkey')
    )
    op.drop_index(op.f('ix_llm_backends_model_name'), table_name='llm_backends')
    op.drop_index('idx_llm_backends_model_name', table_name='llm_backends')
    op.drop_index('idx_llm_backends_enabled', table_name='llm_backends')
    op.drop_index('idx_llm_backends_backend_type', table_name='llm_backends')
    op.drop_table('llm_backends')
    # ### end Alembic commands ###
